github: 'https://github.com/xtreme-mc'
patreon: 
open_collective:
ko_fi: 
tidelift:
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding:
custom: ['https://youtube.com/@xtreme_mc', 'https://instagram.com/xtreme.mc10']
