github:
patreon: 
open_collective:
ko_fi: 
tidelift:
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding:
custom: ['https://youtube.com/@xtreme-mc', 'https://twitter.com/@xtreme.mc10']
